### ISSUE TITLE
Create a separate build for inherited props

### ISSUE THREAD

**Issue by kof** [iamstarkov/jss-expand-all-initial#4]
In jss-isolate, isolation of inherited or all other props is optional. To switch completely to initize lists jss-isolate needs a separate list for inherited props.

**Comment by kof** [comment]
I would call it inherited.js and inherited.css

**Comment by kof** [comment]
We need too avoid one prob though. I would need to require index.js and inherited.js, if index.js contains inherited props as well, it would mean twice loaded inhertied props list. 

I could imagine to require and merge inherited list within index.js.

**Comment by kof** [comment]
Alternatively initize could provide 3 files, inherited.js, non-inherited.js, all.js

**Comment by kof** [comment]
Any progress?

**Comment by kof** [comment]
Looking intto it now.

**Comment by kof** [comment]
color
quotes
text-align

Those are not in the list, because they are filtered by this code

```js
      // we dont need any browser dependent props
      R.propSatisfies(R.anyPass([
        R.test(/browser/i),
        R.test(/useragent/i),
      ]), 'initial'),
```

We definitely need them, can we say that there value should be "initial"?

**Comment by iamstarkov** [comment]
@kof problem with initial for let say color is that initial value will vary in each and every browser

**Comment by iamstarkov** [comment]
text-align and quotes are dependent on locale, so it will vary and its now true as well

**Comment by iamstarkov** [comment]
by "not true" i mean components will might look differently on different websites.

in case of text-align they would be broken

**Comment by kof** [comment]
"box-orient": "inlineAxisHorizontalInXUL",
"text-align": "startOrNamelessValueIfLTRRightIfRTL",

also need initial values

**Comment by kof** [comment]
has been done btw.
