### ISSUE TITLE
Using color broken in Safari

### ISSUE THREAD

**Issue by Andarist** [iamstarkov/jss-expand-all-initial#6]
It seems that Safari doesn't handle properly `currentcolor` value in `-webkit-text-fill-color`. It makes using `color` property impossible.

Small reproduction (needs to be viewed on Safari):
https://jsfiddle.net/7ee8ru1e/

**Comment by kof** [comment]
Yes, I guess you also stumbled over it through jss-isolate, right?

**Comment by kof** [comment]
I think we need to remove from initize non-standard properties completely.

**Comment by kof** [comment]
Need to check if the mdn database has a flag for non-standard properties so they can simply be filtered or we need to maintain a blacklist of them.

**Comment by Andarist** [comment]
Yeah, we've scratched our heads quite a bit because of this. We are using react-styleguidist, which uses jss-isolate.

**Comment by kof** [comment]
This is the corresponding issue https://github.com/styleguidist/react-styleguidist/issues/739

**Comment by Andarist** [comment]
Oh, haven't checked styleguidist's repo for this issue, went straight to the source 😃

**Comment by kof** [comment]
we have a flag status: 'nonstandard'

**Comment by kof** [comment]
Removed all non-standard properties and released in v0.2.0
